# Generated by Django 3.2.9 on 2021-11-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_movie_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='views_count',
        ),
    ]
