# Generated by Django 3.2.9 on 2021-11-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_auto_20211125_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
