# Generated by Django 3.2.9 on 2021-11-26 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_movie_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created']},
        ),
    ]
